import { useState } from 'react'
import { ArrowUpRight, Github, Mail, MapPin, Code2, Server, Database, Workflow, Menu, X, ExternalLink, CheckCircle2 } from 'lucide-react'

const skills = ['Power BI','DAX','Power Query','SQL','Data Modeling','React.js','JavaScript','TypeScript','Next.js','Vite','Tailwind CSS','HTML5','CSS3','REST APIs','FastAPI','Python','PostgreSQL','SQLAlchemy','Git & GitHub','Cloudflare','Render']
const projects = [
{title:'SaaS Executive Analytics',type:'Power BI / Business Intelligence',image:'https://raw.githubusercontent.com/jundaig007/powerbi-analytics-portfolio/main/screenshots/saas-executive-overview.png',imageAlt:'SaaS Executive Analytics Power BI executive dashboard',summary:'An executive Power BI dashboard for SaaS performance monitoring, bringing revenue, customer health, sales pipeline, workforce, and refresh visibility into a single decision-ready view.',challenge:'Give leadership a concise way to monitor business health across fragmented operational domains without relying on separate reports.',outcome:'Built an Executive Overview with ARR, MRR, churn, NPS, win rate, open pipeline, customer risk, sales pipeline, workforce attrition, trend analysis, and period-over-period KPI context.',stack:['Power BI','DAX','Power Query','Data Modeling','SQL'],source:'https://github.com/jundaig007/powerbi-analytics-portfolio',sourceLabel:'View case study'},
{title:'Aurelia Aesthetic Clinic Platform',type:'Healthcare / Full-Stack Business Application',image:'https://image.thum.io/get/width/1200/crop/700/noanimate/https://aesthetic-demo.thedigitalph.com/',imageAlt:'Aurelia aesthetic clinic customer website',summary:'A customer-facing aesthetic clinic experience paired with an administrative platform for managing clinic workflows and digital operations.',challenge:'Create a polished clinic experience for customers while giving staff a practical operational interface behind the scenes.',outcome:'Delivered a responsive clinic website and dedicated admin experience demonstrating service presentation, customer workflows, clinic operations, and business-oriented UX.',stack:['React','Responsive UI','Business Workflows','Admin System'],live:'https://aesthetic-demo.thedigitalph.com/',liveLabel:'Customer website',admin:'https://aesthetic-demo.thedigitalph.com/admin',adminLabel:'Clinic admin'},
{title:'DigitalPH Command Center',type:'Revenue Operations / Executive Platform',image:'https://image.thum.io/get/width/1200/crop/700/noanimate/https://thedigitalph.com/command-center',imageAlt:'DigitalPH Command Center dashboard',summary:'A business operations and revenue command center designed to centralize visibility across lead discovery, qualification, proposals, outreach, contracts, invoicing, onboarding, and client delivery.',challenge:'Reduce fragmentation across the client acquisition and delivery lifecycle while giving management a single operational view.',outcome:'Designed an executive-facing command center around revenue operations, workflow visibility, customer lifecycle management, and decision support.',stack:['React','FastAPI','SQLAlchemy','PostgreSQL'],live:'https://thedigitalph.com/command-center',liveLabel:'Open command center',source:'https://github.com/jundaig007/dghub-v2'},
{title:'Meat Shop POS & Inventory',type:'Full-Stack Business Application',image:'https://image.thum.io/get/width/1200/crop/700/noanimate/https://meat.thedigitalph.com',imageAlt:'Meat Shop POS and Inventory platform',summary:'An operational system for day-to-day meat shop workflows, covering point of sale, purchasing, inventory, customers, delivery, reporting, and product pricing.',challenge:'Bring fragmented store operations into one application while keeping transaction flows fast and practical for everyday use.',outcome:'Built and deployed a full-stack system with product search, CRUD workflows, stock tracking, purchasing, POS operations, customer records, reporting, and API integration.',stack:['React','FastAPI','Python','REST API'],live:'https://meat.thedigitalph.com',liveLabel:'Live system',source:'https://github.com/jundaig007/meat'},
{title:'DigitalPH Business Platform',type:'React / Business Website',image:'https://image.thum.io/get/width/1200/crop/700/noanimate/https://thedigitalph.com',imageAlt:'DigitalPH business website',summary:'A production website and project platform created to present DigitalPH services, case work, and business capabilities through a responsive React experience.',challenge:'Create a credible digital presence that could support client acquisition while remaining easy to extend with new projects and services.',outcome:'Delivered a production-deployed React application with project management features, responsive layouts, service pages, and cloud deployment.',stack:['React','Vite','Tailwind CSS','Cloudflare'],live:'https://thedigitalph.com',liveLabel:'Live website',source:'https://github.com/jundaig007/DGHub-Business-Website'}
]
const experience=[
['Systems Analyst | Business Intelligence & Reporting','UnitedHealth Group (Optum)','Supported director-level and enterprise reporting across multiple business units. Consolidated operational, resource, project-delivery, and support reporting into executive dashboards; partnered with Revenue Operations on billable/non-billable analysis; and collaborated with Data Governance to cleanse, standardize, classify, and consolidate fragmented data into reliable reporting structures. Built and optimized Power BI, TIBCO Spotfire, and SQL solutions supporting 500+ users, worked with datasets exceeding 21 million records, and improved reporting performance by up to 90%.',['Power BI','TIBCO Spotfire','SQL','Data Governance','21M+ Records','500+ Users']],
['Product Analyst | Business Intelligence','Info Alchemy Corporation','Delivered Power BI and analytics solutions for enterprise and government client assignments including DTI, Maybank, and Coca-Cola. Gathered business requirements, defined reporting logic and KPIs, transformed and validated source data, developed data models and dashboards, and performed trend and anomaly analysis. Projects included import/export analytics for DTI, loan-aging reporting for Maybank, and cost-of-goods reporting for Coca-Cola.',['Power BI','Data Analysis','Data Modeling','KPI Development','Requirements Analysis','UAT']],
['Software Developer | Business Systems','Independent & DigitalPH Projects','Design and delivery of production business applications spanning web platforms, REST APIs, operational systems, workflow automation, analytics, and cloud deployment. Projects include the DigitalPH Revenue OS and Command Center, aesthetic clinic platform, and Meat Shop POS & Inventory system.',['React','FastAPI','Python','PostgreSQL','REST APIs','Automation']]
]
const strengths=[['Product thinking','I connect interface decisions to the underlying user and business problem.'],['End-to-end ownership','I can move from requirements and UI implementation through API integration, testing, Git workflows, and deployment.'],['Business systems','My strongest work is software that improves real operational workflows—not just isolated demo interfaces.']]

function App(){
const [menuOpen,setMenuOpen]=useState(false);const closeMenu=()=>setMenuOpen(false);const portraitUrl=`${import.meta.env.BASE_URL}portfolio-portrait.jpg`
return <div className="app">
<header className="nav shell"><a className="brand" href="#top" onClick={closeMenu}><span className="jdLogo" aria-hidden="true"><b>J</b><b>D</b></span> Jun Daig</a><nav className={menuOpen?'open':''}><a href="#about" onClick={closeMenu}>About</a><a href="#skills" onClick={closeMenu}>Skills</a><a href="#projects" onClick={closeMenu}>Projects</a><a href="#experience" onClick={closeMenu}>Experience</a><a className="mobileCta" href="mailto:daigjun444@gmail.com">Contact</a></nav><a className="navCta" href="mailto:daigjun444@gmail.com">Let's talk</a><button className="menuButton" aria-label="Toggle navigation" aria-expanded={menuOpen} onClick={()=>setMenuOpen(!menuOpen)}>{menuOpen?<X/>:<Menu/>}</button></header>
<main id="top">
<section className="hero shell"><div className="heroIntro"><div className="heroCopy"><div className="availability"><i/> Open to Data Analytics, BI, Systems & Full-Stack opportunities</div><p className="eyebrow">POWER BI · SQL · DATA ANALYTICS · FULL-STACK</p><h1>I transform <em>complex data</em> into business insights—and build the systems behind them.</h1><p className="lead">Data analytics and software professional with enterprise experience in Power BI, SQL, TIBCO Spotfire, data governance, data modeling, KPI development, and executive reporting. I analyze and consolidate complex datasets, build decision-ready dashboards, identify trends and anomalies, improve reporting performance, and translate business requirements into reliable analytics solutions. I also develop full-stack applications, APIs, and workflow automation—connecting data, business processes, and software into end-to-end solutions.</p><div className="actions"><a className="primary" href="#projects">Explore selected work <ArrowUpRight size={18}/></a><a className="secondary" href="https://github.com/jundaig007" target="_blank" rel="noreferrer"><Github size={18}/> GitHub profile</a></div></div><div className="portraitCard"><img src={portraitUrl} alt="Jun Daig, React and full-stack developer"/><div className="portraitCaption"><strong>Jun Daig</strong><span>Data Analytics · BI · Systems · Full-Stack</span></div></div></div><div className="quickFacts"><span><MapPin size={16}/> Philippines · Remote-ready</span><span><Database size={16}/> Power BI · SQL · 21M+ Records</span><span><Workflow size={16}/> Data Governance · KPI & Executive Reporting</span></div></section>
<section id="about" className="section shell twoCol"><div><p className="eyebrow">ABOUT ME</p><h2>From raw data to decisions—and from requirements to working systems.</h2></div><div className="aboutCopy"><p>My data analytics work spans enterprise reporting, data cleansing and consolidation, data governance, dimensional modeling, KPI definition, DAX, SQL analysis, dashboard development, validation, reconciliation, trend analysis, anomaly detection, and performance optimization. At UHG / Optum, I supported reporting used by 500+ business users, worked with datasets exceeding 21 million records, and improved reporting performance by up to 90%.</p><p>I also bring software engineering and systems-analysis capability across Python, FastAPI, React, PostgreSQL, REST APIs, automation, and cloud deployment. This allows me to go beyond visualization: I can understand the business requirement, prepare and govern the data, build the analytics layer, and develop applications or workflows that operationalize the insight.</p></div></section>
<section className="valueStrip shell">{strengths.map(([title,text])=><div className="valueItem" key={title}><CheckCircle2 size={18}/><div><h3>{title}</h3><p>{text}</p></div></div>)}</section>
<section id="skills" className="section alt"><div className="shell"><p className="eyebrow">TECHNICAL TOOLKIT</p><h2>Technologies I use to ship products.</h2><div className="skillGrid"><div className="capability"><Code2/><h3>Frontend</h3><p>Responsive interfaces, reusable components, forms, dashboards, search, filtering, and application state.</p></div><div className="capability"><Server/><h3>Backend & APIs</h3><p>REST API integration plus Python/FastAPI services for production business applications.</p></div><div className="capability"><Database/><h3>Data</h3><p>Relational data modeling, SQLAlchemy, PostgreSQL, SQLite, and application data flows.</p></div><div className="capability"><Workflow/><h3>Automation</h3><p>Designing software around repeatable business processes, validations, roles, and operational workflows.</p></div></div><div className="chips">{skills.map(s=><span key={s}>{s}</span>)}</div></div></section>
<section id="projects" className="section shell"><p className="eyebrow">SELECTED WORK</p><div className="sectionHead"><h2>Projects built around real business needs.</h2><p>Production websites, operational systems, and workflow platforms.</p></div><div className="projectGrid">{projects.map((p,i)=><article className="project" key={p.title}>{p.image&&<a className="projectImageWrap" href={p.live||p.source} target="_blank" rel="noreferrer"><img className="projectImage" src={p.image} alt={p.imageAlt||p.title} loading="lazy"/></a>}<div className="projectTop"><div className="projectNo">0{i+1}</div><p className="projectType">{p.type}</p></div><h3>{p.title}</h3><p className="projectSummary">{p.summary}</p><div className="caseStudy"><div><span>Challenge</span><p>{p.challenge}</p></div><div><span>Delivered</span><p>{p.outcome}</p></div></div><div className="projectStack">{p.stack.map(x=><span key={x}>{x}</span>)}</div><div className="projectLinks">{p.live&&<a href={p.live} target="_blank" rel="noreferrer"><ExternalLink size={16}/> {p.liveLabel||'Live project'}</a>}{p.admin&&<a href={p.admin} target="_blank" rel="noreferrer"><ExternalLink size={16}/> {p.adminLabel||'Admin'}</a>}{p.source&&<a href={p.source} target="_blank" rel="noreferrer"><Github size={16}/> {p.sourceLabel||'Source'}</a>}</div></article>)}</div></section>
<section id="experience" className="section alt"><div className="shell"><p className="eyebrow">EXPERIENCE</p><h2>Technical execution backed by product and operations experience.</h2><div className="timeline">{experience.map(([role,company,text,tags],index)=><div className={`experience ${index===0?'experienceFeatured':''}`} key={role+company}><div>{index===0&&<span className="experienceBadge">Enterprise Experience</span>}<h3>{role}</h3><strong>{company}</strong><div className="experienceTags">{tags?.map(tag=><span key={tag}>{tag}</span>)}</div></div><p>{text}</p></div>)}</div></div></section>
<section className="contact shell"><p className="eyebrow">LET'S BUILD SOMETHING USEFUL</p><h2>Need a developer who can understand the product, not just the ticket?</h2><p>I’m open to Data Analytics, Business Intelligence, Systems Analysis, Data & Automation, and Full-Stack opportunities where I can combine data, business understanding, and software engineering.</p><div className="actions center"><a className="primary" href="mailto:daigjun444@gmail.com"><Mail size={18}/> Email me</a><a className="secondary" href="https://github.com/jundaig007" target="_blank" rel="noreferrer"><Github size={18}/> View GitHub</a></div><span className="emailText">daigjun444@gmail.com</span></section>
</main><footer className="shell"><span>© 2026 Jun Daig</span><span>Built with React & Vite · Deployed with GitHub Pages</span></footer></div>}
export default App
