import { useState } from 'react'
import { ArrowUpRight, Github, Mail, MapPin, Code2, Server, Database, Workflow, Menu, X, ExternalLink, CheckCircle2 } from 'lucide-react'

const skills = ['Power BI','DAX','Power Query','SQL','Data Modeling','React.js','JavaScript','TypeScript','Next.js','Vite','Tailwind CSS','HTML5','CSS3','REST APIs','FastAPI','Python','PostgreSQL','SQLAlchemy','Git & GitHub','Cloudflare','Render']
const projects = [
{title:'SaaS Executive Analytics',type:'Power BI / Business Intelligence',summary:'An executive Power BI dashboard for SaaS performance monitoring, bringing revenue, customer health, sales pipeline, workforce, and refresh visibility into a single decision-ready view.',challenge:'Give leadership a concise way to monitor business health across fragmented operational domains without relying on separate reports.',outcome:'Built an Executive Overview with ARR, MRR, churn, NPS, win rate, open pipeline, customer risk, sales pipeline, workforce attrition, trend analysis, and period-over-period KPI context.',stack:['Power BI','DAX','Power Query','Data Modeling','SQL'],source:'https://github.com/jundaig007/powerbi-analytics-portfolio',sourceLabel:'View case study'},
{title:'Aurelia Aesthetic Clinic Platform',type:'Healthcare / Full-Stack Business Application',summary:'A customer-facing aesthetic clinic experience paired with an administrative platform for managing clinic workflows and digital operations.',challenge:'Create a polished clinic experience for customers while giving staff a practical operational interface behind the scenes.',outcome:'Delivered a responsive clinic website and dedicated admin experience demonstrating service presentation, customer workflows, clinic operations, and business-oriented UX.',stack:['React','Responsive UI','Business Workflows','Admin System'],live:'https://aesthetic-demo.thedigitalph.com/',liveLabel:'Customer website',admin:'https://aesthetic-demo.thedigitalph.com/admin',adminLabel:'Clinic admin'},
{title:'DigitalPH Command Center',type:'Revenue Operations / Executive Platform',summary:'A business operations and revenue command center designed to centralize visibility across lead discovery, qualification, proposals, outreach, contracts, invoicing, onboarding, and client delivery.',challenge:'Reduce fragmentation across the client acquisition and delivery lifecycle while giving management a single operational view.',outcome:'Designed an executive-facing command center around revenue operations, workflow visibility, customer lifecycle management, and decision support.',stack:['React','FastAPI','SQLAlchemy','PostgreSQL'],live:'https://thedigitalph.com/command-center',liveLabel:'Open command center',source:'https://github.com/jundaig007/dghub-v2'},
{title:'Meat Shop POS & Inventory',type:'Full-Stack Business Application',summary:'An operational system for day-to-day meat shop workflows, covering point of sale, purchasing, inventory, customers, delivery, reporting, and product pricing.',challenge:'Bring fragmented store operations into one application while keeping transaction flows fast and practical for everyday use.',outcome:'Built and deployed a full-stack system with product search, CRUD workflows, stock tracking, purchasing, POS operations, customer records, reporting, and API integration.',stack:['React','FastAPI','Python','REST API'],live:'https://meat.thedigitalph.com',liveLabel:'Live system',source:'https://github.com/jundaig007/meat'},
{title:'DigitalPH Business Platform',type:'React / Business Website',summary:'A production website and project platform created to present DigitalPH services, case work, and business capabilities through a responsive React experience.',challenge:'Create a credible digital presence that could support client acquisition while remaining easy to extend with new projects and services.',outcome:'Delivered a production-deployed React application with project management features, responsive layouts, service pages, and cloud deployment.',stack:['React','Vite','Tailwind CSS','Cloudflare'],live:'https://thedigitalph.com',liveLabel:'Live website',source:'https://github.com/jundaig007/DGHub-Business-Website'}
]
const experience=[['Systems Analyst','UHG - Optum','Worked with enterprise systems, requirements, process improvement, and cross-functional teams—experience that shaped how I translate business needs into technical solutions.'],['Product Analyst','Info Alchemy Corp.','Handled product analysis, requirements definition, stakeholder coordination, and technology-driven solution planning.'],['COO','Espasio Construction','Led operations and business processes, building the practical management perspective I now bring into software development.'],['Software Developer','Independent & Business Projects','Designing and delivering responsive web applications, operational systems, REST APIs, automation workflows, and production deployments.']]
const strengths=[['Product thinking','I connect interface decisions to the underlying user and business problem.'],['End-to-end ownership','I can move from requirements and UI implementation through API integration, testing, Git workflows, and deployment.'],['Business systems','My strongest work is software that improves real operational workflows—not just isolated demo interfaces.']]

function App(){
const [menuOpen,setMenuOpen]=useState(false);const closeMenu=()=>setMenuOpen(false);const portraitUrl=`${import.meta.env.BASE_URL}portfolio-portrait.jpg`
return <div className="app">
<header className="nav shell"><a className="brand" href="#top" onClick={closeMenu}><span>JD</span> Jun Daig</a><nav className={menuOpen?'open':''}><a href="#about" onClick={closeMenu}>About</a><a href="#skills" onClick={closeMenu}>Skills</a><a href="#projects" onClick={closeMenu}>Projects</a><a href="#experience" onClick={closeMenu}>Experience</a><a className="mobileCta" href="mailto:daigjun444@gmail.com">Contact</a></nav><a className="navCta" href="mailto:daigjun444@gmail.com">Let's talk</a><button className="menuButton" aria-label="Toggle navigation" aria-expanded={menuOpen} onClick={()=>setMenuOpen(!menuOpen)}>{menuOpen?<X/>:<Menu/>}</button></header>
<main id="top">
<section className="hero shell"><div className="heroIntro"><div className="heroCopy"><div className="availability"><i/> Open to Front-End & Full-Stack opportunities</div><p className="eyebrow">REACT · FRONT-END · FULL-STACK</p><h1>I build digital products that turn <em>complex workflows</em> into simple experiences.</h1><p className="lead">React-focused developer with a background in systems analysis, product analysis, and operations. I build responsive business applications, connect them to reliable APIs, and take products from requirements through production deployment.</p><div className="actions"><a className="primary" href="#projects">Explore selected work <ArrowUpRight size={18}/></a><a className="secondary" href="https://github.com/jundaig007" target="_blank" rel="noreferrer"><Github size={18}/> GitHub profile</a></div></div><div className="portraitCard"><img src={portraitUrl} alt="Jun Daig, React and full-stack developer"/><div className="portraitCaption"><strong>Jun Daig</strong><span>React · Full-Stack · Product-minded</span></div></div></div><div className="quickFacts"><span><MapPin size={16}/> Philippines · Remote-ready</span><span><Code2 size={16}/> React & modern JavaScript</span><span><Server size={16}/> Frontend + API integration</span></div></section>
<section id="about" className="section shell twoCol"><div><p className="eyebrow">ABOUT ME</p><h2>Engineering with a business mindset.</h2></div><div className="aboutCopy"><p>I combine hands-on development with experience in systems analysis, product analysis, and business operations. That means I approach frontend work by asking two questions: what does the user need, and what outcome does the business need?</p><p>I’m comfortable working across responsive UI development, reusable components, API integration, data-driven applications, testing, Git/GitHub workflows, and cloud deployment.</p></div></section>
<section className="valueStrip shell">{strengths.map(([title,text])=><div className="valueItem" key={title}><CheckCircle2 size={18}/><div><h3>{title}</h3><p>{text}</p></div></div>)}</section>
<section id="skills" className="section alt"><div className="shell"><p className="eyebrow">TECHNICAL TOOLKIT</p><h2>Technologies I use to ship products.</h2><div className="skillGrid"><div className="capability"><Code2/><h3>Frontend</h3><p>Responsive interfaces, reusable components, forms, dashboards, search, filtering, and application state.</p></div><div className="capability"><Server/><h3>Backend & APIs</h3><p>REST API integration plus Python/FastAPI services for production business applications.</p></div><div className="capability"><Database/><h3>Data</h3><p>Relational data modeling, SQLAlchemy, PostgreSQL, SQLite, and application data flows.</p></div><div className="capability"><Workflow/><h3>Automation</h3><p>Designing software around repeatable business processes, validations, roles, and operational workflows.</p></div></div><div className="chips">{skills.map(s=><span key={s}>{s}</span>)}</div></div></section>
<section id="projects" className="section shell"><p className="eyebrow">SELECTED WORK</p><div className="sectionHead"><h2>Projects built around real business needs.</h2><p>Production websites, operational systems, and workflow platforms.</p></div><div className="projectGrid">{projects.map((p,i)=><article className="project" key={p.title}><div className="projectTop"><div className="projectNo">0{i+1}</div><p className="projectType">{p.type}</p></div><h3>{p.title}</h3><p className="projectSummary">{p.summary}</p><div className="caseStudy"><div><span>Challenge</span><p>{p.challenge}</p></div><div><span>Delivered</span><p>{p.outcome}</p></div></div><div className="projectStack">{p.stack.map(x=><span key={x}>{x}</span>)}</div><div className="projectLinks">{p.live&&<a href={p.live} target="_blank" rel="noreferrer"><ExternalLink size={16}/> {p.liveLabel||'Live project'}</a>}{p.admin&&<a href={p.admin} target="_blank" rel="noreferrer"><ExternalLink size={16}/> {p.adminLabel||'Admin'}</a>}{p.source&&<a href={p.source} target="_blank" rel="noreferrer"><Github size={16}/> {p.sourceLabel||'Source'}</a>}</div></article>)}</div></section>
<section id="experience" className="section alt"><div className="shell"><p className="eyebrow">EXPERIENCE</p><h2>Technical execution backed by product and operations experience.</h2><div className="timeline">{experience.map(([role,company,text],index)=><div className={`experience ${index===0?'experienceFeatured':''}`} key={role+company}><div>{index===0&&<span className="experienceBadge">Most Recent Experience</span>}<h3>{role}</h3><strong>{company}</strong></div><p>{text}</p></div>)}</div></div></section>
<section className="contact shell"><p className="eyebrow">LET'S BUILD SOMETHING USEFUL</p><h2>Need a developer who can understand the product, not just the ticket?</h2><p>I’m open to Front-End, React, Full-Stack, and product-focused software development opportunities.</p><div className="actions center"><a className="primary" href="mailto:daigjun444@gmail.com"><Mail size={18}/> Email me</a><a className="secondary" href="https://github.com/jundaig007" target="_blank" rel="noreferrer"><Github size={18}/> View GitHub</a></div><span className="emailText">daigjun444@gmail.com</span></section>
</main><footer className="shell"><span>© 2026 Jun Daig</span><span>Built with React & Vite · Deployed with GitHub Pages</span></footer></div>}
export default App
